### ISSUE TITLE
Blank Screen on Logout

### ISSUE THREAD

**Issue by GaneshKandu** [bigprof/Resources-Utilization-Viewer--RUView-#1] opened 2015-10-26 06:38 UTC
Hi My Name is Ganesh Kandu
I Have Installed RUView,
and I am getting Blank screen when I am logout from this url "<path>/admin/pageHome.php"

**Comment by GaneshKandu** [comment] 2015-10-26 06:39
@GaneshKandu
GaneshKandu commented a minute ago

Hi My Name is Ganesh Kandu
I Have Installed RUView v5.41,
and I am getting Blank screen when I am logout from this url "/admin/pageHome.php"

**Comment by bigprof** [comment] 2015-10-29 17:03
Please specify the browser you are using and which version. I was unable to reproduce this issue on Firefox (version 41) not on Chrome (version 46).

**Comment by GaneshKandu** [comment] 2015-11-05 05:45
FireFox and Mozilla Developers V 41.0.2
File Version 41.0.2.5765

I am Tried in Chrome its working in Chrome
but Not Working in FireFox and Mozilla Developers V 41.0.2

**Comment by bigprof** [comment] 2015-11-05 10:02
Thanks for the update. I haven't been able to reproduce this issue so far on Firefox. Since you reported it working on Chrome, I'll close the issue for now.

**Closed by bigprof** 2015-11-05 10:02 UTC
